name: Auto Update

on:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  versions:
    runs-on: ubuntu-latest

    name: Get Versions

    outputs:
      current: ${{ steps.current-version.outputs.content }}
      latest: ${{ steps.latest-version.outputs.release }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - id: current-version
      name: Get current Font Awesome version
      uses: juliangruber/read-file-action@v1
      with:
        trim: true
        path: ./.version

    - id: latest-version
      name: Get latest Font Awesome version
      uses: pozetroninc/github-action-get-latest-release@v0.5.0
      with:
        repository: FortAwesome/Font-Awesome

    - name: Output versions
      run: |
        echo "Current release: ${{ steps.current-version.outputs.content }}"
        echo "Latest release: ${{ steps.latest-version.outputs.release }}"

  update:
    runs-on: ubuntu-latest

    name: Update Font Awesome

    needs: [versions]

    if: needs.versions.outputs.current != needs.versions.outputs.latest

    env:
      CURRENT_VERSION: ${{ needs.versions.outputs.current }}
      LATEST_VERSION: ${{ needs.versions.outputs.latest }}
      BRANCH: feature/update-${{ needs.versions.outputs.latest }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        tools: composer
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --prefer-dist --no-progress --ansi

    - name: Update to latest version
      run: npm install "@fortawesome/fontawesome-free@${{ env.LATEST_VERSION }}" --save-dev

    - name: Compile icons to resources directory
      run: ./vendor/bin/blade-icons-generate

    - name: Update version in ".version"
      run: echo ${{ env.LATEST_VERSION }}>./.version

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@master
      with:
        create_branch: true
        commit_message: "chore: update to Font Awesome v${{ env.LATEST_VERSION }}"
        commit_author: GitHub Action <noreply@github.com>
        branch: ${{ env.BRANCH }}

    - name: Update test snapshots
      run: php vendor/bin/pest -d --update-snapshots

    - name: Commit changes
      id: commit_snapshots
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "tests: update snapshots for v${{ env.LATEST_VERSION }}"
        commit_author: GitHub Action <noreply@github.com>
        branch: ${{ env.BRANCH }}
        file_pattern: 'tests/__snapshots__/*'

    - name: Create PR for latest version
      uses: peter-evans/create-pull-request@v3
      with:
        title: "chore: update to Font Awesome v${{ env.LATEST_VERSION }}"
        body: |
          This updates from [${{ env.CURRENT_VERSION }}](https://github.com/FortAwesome/Font-Awesome/releases/tag/${{ env.CURRENT_VERSION }}) to [${{ env.LATEST_VERSION }}](https://github.com/FortAwesome/Font-Awesome/releases/tag/${{ env.LATEST_VERSION }}).

          Check out the differences: [`${{ env.CURRENT_VERSION }}` ... `${{ env.LATEST_VERSION }}`](https://github.com/FortAwesome/Font-Awesome/compare/${{ env.CURRENT_VERSION }}...${{ env.LATEST_VERSION }})

          Please check for any breaking or notable changes before merging.
          - [Changelog](https://github.com/FortAwesome/Font-Awesome/blob/${{ env.LATEST_VERSION }}/CHANGELOG.md#change-log)
          - [Upgrade Guide](https://github.com/FortAwesome/Font-Awesome/blob/${{ env.LATEST_VERSION }}/UPGRADING.md#upgrading-guide)

          Please also check that the snapshots were updated successfully in commit: ${{ steps.commit_snapshots.outputs.commit_hash }}.
